[package]
name = "waybackwhen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slack-morphism = { version = "1.6", features = ["hyper", "axum"] }
